let language = [
    {
        "category": "basic",
        "verbs": [
            {"verb":"Essere","conjugation":{"presente":{"io":"sono","tu":"sei","lei":"è","noi":"siamo","voi":"siete","loro":"sono"},"imperfetto":{"io":"ero","tu":"eri","lei":"era","noi":"eravamo","voi":"eravate","loro":"erano"},"passato":{"io":"sono stato/a","tu":"sei stato/a","lei":"è stato/a","noi":"siamo stati/e","voi":"siete stati/e","loro":"sono stati/e"},"futuro":{"io":"sarò","tu":"sarai","lei":"sarà","noi":"saremo","voi":"sarete","loro":"saranno"}}},
            {"verb":"Avere","conjugation":{"presente":{"io":"ho","tu":"hai","lei":"ha","noi":"abbiamo","voi":"avete","loro":"hanno"},"imperfetto":{"io":"avevo","tu":"avevi","lei":"aveva","noi":"avevamo","voi":"avevate","loro":"avevano"},"passato":{"io":"ho avuto","tu":"hai avuto","lei":"ha avuto","noi":"abbiamo avuto","voi":"avete avuto","loro":"hanno avuto"},"futuro":{"io":"avrò","tu":"avrai","lei":"avrà","noi":"avremo","voi":"avrete","loro":"avranno"}}}
        ]
    },
    {
        "category": "essential",
        "verbs": [
            {"verb":"Potere","conjugation":{"presente":{"io":"posso","tu":"puoi","lei":"può","noi":"possiamo","voi":"potete","loro":"possono"},"imperfetto":{"io":"potevo","tu":"potevi","lei":"poteva","noi":"potevamo","voi":"potevate","loro":"potevano"},"passato":{"io":"ho potuto","tu":"hai potuto","lei":"ha potuto","noi":"abbiamo potuto","voi":"avete potuto","loro":"hanno potuto"},"futuro":{"io":"potrò","tu":"potrai","lei":"potrà","noi":"potremo","voi":"potrete","loro":"potranno"}}},
            {"verb":"Volere","conjugation":{"presente":{"io":"voglio","tu":"vuoi","lei":"vuole","noi":"vogliamo","voi":"volete","loro":"vogliono"},"imperfetto":{"io":"volevo","tu":"volevi","lei":"voleva","noi":"volevamo","voi":"volevate","loro":"volevano"},"passato":{"io":"ho voluto","tu":"hai voluto","lei":"ha voluto","noi":"abbiamo voluto","voi":"avete voluto","loro":"hanno voluto"},"futuro":{"io":"vorrò","tu":"vorrai","lei":"vorrà","noi":"vorremo","voi":"vorrete","loro":"vorranno"}}},
            {"verb":"Dovere","conjugation":{"presente":{"io":"devo","tu":"devi","lei":"deve","noi":"dobbiamo","voi":"dovete","loro":"devono"},"imperfetto":{"io":"dovevo","tu":"dovevi","lei":"doveva","noi":"dovevamo","voi":"dovevate","loro":"dovevano"},"passato":{"io":"ho dovuto","tu":"hai dovuto","lei":"ha dovuto","noi":"abbiamo dovuto","voi":"avete dovuto","loro":"hanno dovuto"},"futuro":{"io":"dovrò","tu":"dovrai","lei":"dovrà","noi":"dovremo","voi":"dovrete","loro":"dovranno"}}},
            {"verb":"Sapere","conjugation":{"presente":{"io":"so","tu":"sai","lei":"sa","noi":"sappiamo","voi":"sapete","loro":"sanno"},"imperfetto":{"io":"sapevo","tu":"sapevi","lei":"sapeva","noi":"sapevamo","voi":"sapevate","loro":"sapevano"},"passato":{"io":"ho saputo","tu":"hai saputo","lei":"ha saputo","noi":"abbiamo saputo","voi":"avete saputo","loro":"hanno saputo"},"futuro":{"io":"saprò","tu":"saprai","lei":"saprà","noi":"sapremo","voi":"saprete","loro":"sapranno"}}},
            {"verb":"Stare","conjugation":{"presente":{"io":"sto","tu":"stai","lei":"sta","noi":"stiamo","voi":"state","loro":"stanno"},"imperfetto":{"io":"stavo","tu":"stavi","lei":"stava","noi":"stavamo","voi":"stavate","loro":"stavano"},"passato":{"io":"sono stato/a","tu":"sei stato/a","lei":"è stato/a","noi":"siamo stati/e","voi":"siete stati/e","loro":"sono stati/e"},"futuro":{"io":"starò","tu":"starai","lei":"starà","noi":"staremo","voi":"starete","loro":"staranno"}}},
            {"verb":"Andare","conjugation":{"presente":{"io":"vado","tu":"vai","lei":"va","noi":"andiamo","voi":"andate","loro":"vanno"},"imperfetto":{"io":"andavo","tu":"andavi","lei":"andava","noi":"andavamo","voi":"andavate","loro":"andavano"},"passato":{"io":"sono andato/a","tu":"sei andato/a","lei":"è andato/a","noi":"siamo andati/e","voi":"siete andati/e","loro":"sono andati/e"},"futuro":{"io":"andrò","tu":"andrai","lei":"andrà","noi":"andremo","voi":"andrete","loro":"andranno"}}}
        ]
    },
    {
        "category": "frequent",
        "verbs": [
            {"verb":"Fare","conjugation":{"presente":{"io":"faccio","tu":"fai","lei":"fa","noi":"facciamo","voi":"fate","loro":"fanno"},"imperfetto":{"io":"facevo","tu":"facevi","lei":"faceva","noi":"facevamo","voi":"facevate","loro":"facevano"},"passato":{"io":"ho fatto","tu":"hai fatto","lei":"ha fatto","noi":"abbiamo fatto","voi":"avete fatto","loro":"hanno fatto"},"futuro":{"io":"farò","tu":"farai","lei":"farà","noi":"faremo","voi":"farete","loro":"faranno"}}},
            {"verb":"Dire","conjugation":{"presente":{"io":"dico","tu":"dici","lei":"dice","noi":"diciamo","voi":"dite","loro":"dicono"},"imperfetto":{"io":"dicevo","tu":"dicevi","lei":"diceva","noi":"dicevamo","voi":"dicevate","loro":"dicevano"},"passato":{"io":"ho detto","tu":"hai detto","lei":"ha detto","noi":"abbiamo detto","voi":"avete detto","loro":"hanno detto"},"futuro":{"io":"dirò","tu":"dirai","lei":"dirà","noi":"diremo","voi":"direte","loro":"diranno"}}},
            {"verb":"Venire","conjugation":{"presente":{"io":"vengo","tu":"vieni","lei":"viene","noi":"veniamo","voi":"venite","loro":"vengono"},"imperfetto":{"io":"venivo","tu":"venivi","lei":"veniva","noi":"venivamo","voi":"venivate","loro":"venivano"},"passato":{"io":"sono venuto/a","tu":"sei venuto/a","lei":"è venuto/a","noi":"siamo venuti/e","voi":"siete venuti/e","loro":"sono venuti/e"},"futuro":{"io":"verrò","tu":"verrai","lei":"verrà","noi":"verremo","voi":"verrete","loro":"verranno"}}},
            {"verb":"Dare","conjugation":{"presente":{"io":"do","tu":"dai","lei":"dà","noi":"diamo","voi":"date","loro":"danno"},"imperfetto":{"io":"davo","tu":"davi","lei":"dava","noi":"davamo","voi":"davate","loro":"davano"},"passato":{"io":"ho dato","tu":"hai dato","lei":"ha dato","noi":"abbiamo dato","voi":"avete dato","loro":"hanno dato"},"futuro":{"io":"darò","tu":"darai","lei":"darà","noi":"daremo","voi":"darete","loro":"daranno"}}},
            {"verb":"Vedere","conjugation":{"presente":{"io":"vedo","tu":"vedi","lei":"vede","noi":"vediamo","voi":"vedete","loro":"vedono"},"imperfetto":{"io":"vedevo","tu":"vedevi","lei":"vedeva","noi":"vedevamo","voi":"vedevate","loro":"vedevano"},"passato":{"io":"ho visto","tu":"hai visto","lei":"ha visto","noi":"abbiamo visto","voi":"avete visto","loro":"hanno visto"},"futuro":{"io":"vedrò","tu":"vedrai","lei":"vedrà","noi":"vedremo","voi":"vedrete","loro":"vedranno"}}},
            {"verb":"Parlare","conjugation":{"presente":{"io":"parlo","tu":"parli","lei":"parla","noi":"parliamo","voi":"parlate","loro":"parlano"},"imperfetto":{"io":"parlavo","tu":"parlavi","lei":"parlava","noi":"parlavamo","voi":"parlavate","loro":"parlavano"},"passato":{"io":"ho parlato","tu":"hai parlato","lei":"ha parlato","noi":"abbiamo parlato","voi":"avete parlato","loro":"hanno parlato"},"futuro":{"io":"parlerò","tu":"parlerai","lei":"parlerà","noi":"parleremo","voi":"parlerete","loro":"parleranno"}}},
            {"verb":"Trovare","conjugation":{"presente":{"io":"trovo","tu":"trovi","lei":"trova","noi":"troviamo","voi":"trovate","loro":"trovano"},"imperfetto":{"io":"trovavo","tu":"trovavi","lei":"trovava","noi":"trovavamo","voi":"trovavate","loro":"trovavano"},"passato":{"io":"ho trovato","tu":"hai trovato","lei":"ha trovato","noi":"abbiamo trovato","voi":"avete trovato","loro":"hanno trovato"},"futuro":{"io":"troverò","tu":"troverai","lei":"troverà","noi":"troveremo","voi":"troverete","loro":"troveranno"}}},
            {"verb":"Chiedere","conjugation":{"presente":{"io":"chiedo","tu":"chiedi","lei":"chiede","noi":"chiediamo","voi":"chiedete","loro":"chiedono"},"imperfetto":{"io":"chiedevo","tu":"chiedevi","lei":"chiedeva","noi":"chiedevamo","voi":"chiedevate","loro":"chiedevano"},"passato":{"io":"ho chiesto","tu":"hai chiesto","lei":"ha chiesto","noi":"abbiamo chiesto","voi":"avete chiesto","loro":"hanno chiesto"},"futuro":{"io":"chiederò","tu":"chiederai","lei":"chiederà","noi":"chiederemo","voi":"chiederete","loro":"chiederanno"}}},
            {"verb":"Mettere","conjugation":{"presente":{"io":"metto","tu":"metti","lei":"mette","noi":"mettiamo","voi":"mettete","loro":"mettono"},"imperfetto":{"io":"mettevo","tu":"mettevi","lei":"metteva","noi":"mettevamo","voi":"mettevate","loro":"mettevano"},"passato":{"io":"ho messo","tu":"hai messo","lei":"ha messo","noi":"abbiamo messo","voi":"avete messo","loro":"hanno messo"},"futuro":{"io":"metterò","tu":"metterai","lei":"metterà","noi":"metteremo","voi":"metterete","loro":"metteranno"}}},
            {"verb":"Prendere","conjugation":{"presente":{"io":"prendo","tu":"prendi","lei":"prende","noi":"prendiamo","voi":"prendete","loro":"prendono"},"imperfetto":{"io":"prendevo","tu":"prendevi","lei":"prendeva","noi":"prendevamo","voi":"prendevate","loro":"prendevano"},"passato":{"io":"ho preso","tu":"hai preso","lei":"ha preso","noi":"abbiamo preso","voi":"avete preso","loro":"hanno preso"},"futuro":{"io":"prenderò","tu":"prenderai","lei":"prenderà","noi":"prenderemo","voi":"prenderete","loro":"prenderanno"}}},
            {"verb":"Sentire","conjugation":{"presente":{"io":"sento","tu":"senti","lei":"sente","noi":"sentiamo","voi":"sentite","loro":"sentono"},"imperfetto":{"io":"sentivo","tu":"sentivi","lei":"sentiva","noi":"sentivamo","voi":"sentivate","loro":"sentivano"},"passato":{"io":"ho sentito","tu":"hai sentito","lei":"ha sentito","noi":"abbiamo sentito","voi":"avete sentito","loro":"hanno sentito"},"futuro":{"io":"sentirò","tu":"sentirai","lei":"sentirà","noi":"sentiremo","voi":"sentirete","loro":"sentiranno"}}},
            {"verb":"Lasciare","conjugation":{"presente":{"io":"lascio","tu":"lasci","lei":"lascia","noi":"lasciamo","voi":"lasciate","loro":"lasciano"},"imperfetto":{"io":"lasciavo","tu":"lasciavi","lei":"lasciava","noi":"lasciavamo","voi":"lasciavate","loro":"lasciavano"},"passato":{"io":"ho lasciato","tu":"hai lasciato","lei":"ha lasciato","noi":"abbiamo lasciato","voi":"avete lasciato","loro":"hanno lasciato"},"futuro":{"io":"lascerò","tu":"lascerai","lei":"lascerà","noi":"lasceremo","voi":"lascerete","loro":"lasceranno"}}},
            {"verb":"Capire","conjugation":{"presente":{"io":"capisco","tu":"capisci","lei":"capisce","noi":"capisciamo","voi":"capite","loro":"capiscono"},"imperfetto":{"io":"capivo","tu":"capivi","lei":"capiva","noi":"capivamo","voi":"capivate","loro":"capivano"},"passato":{"io":"ho capito","tu":"hai capito","lei":"ha capito","noi":"abbiamo capito","voi":"avete capito","loro":"hanno capito"},"futuro":{"io":"capirò","tu":"capirai","lei":"capirà","noi":"capiremo","voi":"capirete","loro":"capiranno"}}},
            {"verb":"Tenere","conjugation":{"presente":{"io":"tengo","tu":"tieni","lei":"tiene","noi":"teniamo","voi":"tenete","loro":"tengono"},"imperfetto":{"io":"tenevo","tu":"tenevi","lei":"teneva","noi":"tenevo","voi":"tenevi","loro":"tenevano"},"passato":{"io":"ho tenuto","tu":"hai tenuto","lei":"ha tenuto","noi":"abbiamo tenuto","voi":"avete tenuto","loro":"hanno tenuto"},"futuro":{"io":"terrò","tu":"terrai","lei":"terrà","noi":"terremo","voi":"terrete","loro":"terranno"}}},
            {"verb":"Portare","conjugation":{"presente":{"io":"porto","tu":"porti","lei":"porta","noi":"portiamo","voi":"portate","loro":"portano"},"imperfetto":{"io":"portavo","tu":"portavi","lei":"portava","noi":"portavamo","voi":"portavate","loro":"portavano"},"passato":{"io":"ho portato","tu":"hai portato","lei":"ha portato","noi":"abbiamo portato","voi":"avete portato","loro":"hanno portato"},"futuro":{"io":"porterò","tu":"porterai","lei":"porterà","noi":"porteremo","voi":"porterete","loro":"porteranno"}}},
            {"verb":"Scrivere","conjugation":{"presente":{"io":"scrivo","tu":"scrivi","lei":"scrive","noi":"scriviamo","voi":"scrivete","loro":"scrivono"},"imperfetto":{"io":"scrivevo","tu":"scrivevi","lei":"scriveva","noi":"scrivevamo","voi":"scrivevate","loro":"scrivevano"},"passato":{"io":"ho scritto","tu":"hai scritto","lei":"ha scritto","noi":"abbiamo scritto","voi":"avete scritto","loro":"hanno scritto"},"futuro":{"io":"scriverò","tu":"scriverai","lei":"scriverà","noi":"scriveremo","voi":"scriverete","loro":"scriveranno"}}},
            {"verb":"Leggere","conjugation":{"presente":{"io":"leggo","tu":"leggi","lei":"legge","noi":"leggiamo","voi":"leggete","loro":"leggono"},"imperfetto":{"io":"leggevo","tu":"leggevi","lei":"leggeva","noi":"leggevamo","voi":"leggevate","loro":"leggevano"},"passato":{"io":"ho letto","tu":"hai letto","lei":"ha letto","noi":"abbiamo letto","voi":"avete letto","loro":"hanno letto"},"futuro":{"io":"leggerò","tu":"leggerai","lei":"leggerà","noi":"leggeremo","voi":"leggerete","loro":"leggeranno"}}},
            {"verb":"Mangiare","conjugation":{"presente":{"io":"mangio","tu":"mangi","lei":"mangia","noi":"mangiamo","voi":"mangiate","loro":"mangiano"},"imperfetto":{"io":"mangiavo","tu":"mangiavi","lei":"mangiava","noi":"mangiavamo","voi":"mangiavate","loro":"mangiavano"},"passato":{"io":"ho mangiato","tu":"hai mangiato","lei":"ha mangiato","noi":"abbiamo mangiato","voi":"avete mangiato","loro":"hanno mangiato"},"futuro":{"io":"mangerò","tu":"mangerai","lei":"mangerà","noi":"mangeremo","voi":"mangerete","loro":"mangeranno"}}},
            {"verb":"Bere","conjugation":{"presente":{"io":"bevo","tu":"bevi","lei":"beve","noi":"beviamo","voi":"bevete","loro":"bevono"},"imperfetto":{"io":"bevevo","tu":"bevevi","lei":"beveva","noi":"bevevamo","voi":"bevevate","loro":"bevevano"},"passato":{"io":"ho bevuto","tu":"hai bevuto","lei":"ha bevuto","noi":"abbiamo bevuto","voi":"avete bevuto","loro":"hanno bevuto"},"futuro":{"io":"berrò","tu":"berrai","lei":"berrà","noi":"berremo","voi":"berrete","loro":"berranno"}}},
            {"verb":"Vivere","conjugation":{"presente":{"io":"vivo","tu":"vivi","lei":"vive","noi":"viviamo","voi":"vivete","loro":"vivono"},"imperfetto":{"io":"vivevo","tu":"vivevi","lei":"viveva","noi":"vivevamo","voi":"vivevate","loro":"vivevano"},"passato":{"io":"ho vissuto","tu":"hai vissuto","lei":"ha vissuto","noi":"abbiamo vissuto","voi":"avete vissuto","loro":"hanno vissuto"},"futuro":{"io":"vivrò","tu":"vivrai","lei":"vivrà","noi":"vivremo","voi":"vivrete","loro":"vivranno"}}},
            {"verb":"Amare","conjugation":{"presente":{"io":"amo","tu":"ami","lei":"ama","noi":"amiamo","voi":"amate","loro":"amano"},"imperfetto":{"io":"amavo","tu":"amavi","lei":"amava","noi":"amavamo","voi":"amavate","loro":"amavano"},"passato":{"io":"ho amato","tu":"hai amato","lei":"ha amato","noi":"abbiamo amato","voi":"avete amato","loro":"hanno amato"},"futuro":{"io":"amerò","tu":"amerai","lei":"amerà","noi":"ameremo","voi":"amerete","loro":"ameranno"}}},
            {"verb":"Piacere","conjugation":{"presente":{"io":"piace","tu":"piaci","lei":"piace","noi":"piacciamo","voi":"piacete","loro":"piacciono"},"imperfetto":{"io":"piacevo","tu":"piacevi","lei":"piaceva","noi":"piacevamo","voi":"piacevate","loro":"piacevano"},"passato":{"io":"è piaciuto/a","tu":"è piaciuto/a","lei":"è piaciuto/a","noi":"sono piaciuti/e","voi":"sono piaciuti/e","loro":"sono piaciuti/e"},"futuro":{"io":"piacerò","tu":"piacerai","lei":"piacerà","noi":"piaceremo","voi":"piacerete","loro":"piaceranno"}}},
            {"verb":"Godere","conjugation":{"presente":{"io":"godo","tu":"godi","lei":"gode","noi":"godiamo","voi":"godete","loro":"godono"},"imperfetto":{"io":"godevo","tu":"godevi","lei":"godeva","noi":"godevamo","voi":"godevate","loro":"godevano"},"passato":{"io":"ho goduto","tu":"hai goduto","lei":"ha goduto","noi":"abbiamo goduto","voi":"avete goduto","loro":"hanno goduto"},"futuro":{"io":"godrò","tu":"godrai","lei":"godrà","noi":"godremo","voi":"godrete","loro":"godranno"}}}
        ]
    },
    {
        "category": "daily",
        "verbs": [
            {"verb":"Aprire","conjugation":{"presente":{"io":"apro","tu":"apri","lei":"apre","noi":"apriamo","voi":"aprite","loro":"aprono"},"imperfetto":{"io":"aprivo","tu":"aprivi","lei":"apriva","noi":"apriamo","voi":"aprivate","loro":"aprivano"},"passato":{"io":"ho aperto","tu":"hai aperto","lei":"ha aperto","noi":"abbiamo aperto","voi":"avete aperto","loro":"hanno aperto"},"futuro":{"io":"aprirò","tu":"aprirai","lei":"aprirà","noi":"apriremo","voi":"aprirete","loro":"apriranno"}}},
            {"verb":"Chiudere","conjugation":{"presente":{"io":"chiudo","tu":"chiudi","lei":"chiude","noi":"chiudiamo","voi":"chiudete","loro":"chiudono"},"imperfetto":{"io":"chiudevo","tu":"chiudevi","lei":"chiudeva","noi":"chiudevamo","voi":"chiudevate","loro":"chiudevano"},"passato":{"io":"ho chiuso","tu":"hai chiuso","lei":"ha chiuso","noi":"abbiamo chiuso","voi":"avete chiuso","loro":"hanno chiuso"},"futuro":{"io":"chiuderò","tu":"chiuderai","lei":"chiuderà","noi":"chiuderemo","voi":"chiuderete","loro":"chiuderanno"}}},
            {"verb":"Comprare","conjugation":{"presente":{"io":"compro","tu":"compri","lei":"compra","noi":"comperiamo","voi":"comperate","loro":"comprano"},"imperfetto":{"io":"compravo","tu":"compravi","lei":"comprava","noi":"compravamo","voi":"compravate","loro":"compravano"},"passato":{"io":"ho comprato","tu":"hai comprato","lei":"ha comprato","noi":"abbiamo comprato","voi":"avete comprato","loro":"hanno comprato"},"futuro":{"io":"comprerò","tu":"comprerai","lei":"comprerà","noi":"compreremo","voi":"comprerete","loro":"compreranno"}}},
            {"verb":"Pagare","conjugation":{"presente":{"io":"pago","tu":"paghi","lei":"paga","noi":"paghiamo","voi":"pagate","loro":"pagano"},"imperfetto":{"io":"pagavo","tu":"pagavi","lei":"pagava","noi":"pagavamo","voi":"pagavate","loro":"pagavano"},"passato":{"io":"ho pagato","tu":"hai pagato","lei":"ha pagato","noi":"abbiamo pagato","voi":"avete pagato","loro":"hanno pagato"},"futuro":{"io":"pagherò","tu":"pagherai","lei":"pagherà","noi":"pagheremo","voi":"pagherete","loro":"pagheranno"}}},
            {"verb":"Lavorare","conjugation":{"presente":{"io":"lavoro","tu":"lavori","lei":"lavora","noi":"lavoriamo","voi":"lavorate","loro":"lavorano"},"imperfetto":{"io":"lavoravo","tu":"lavoravi","lei":"lavorava","noi":"lavoravamo","voi":"lavoravate","loro":"lavoravano"},"passato":{"io":"ho lavorato","tu":"hai lavorato","lei":"ha lavorato","noi":"abbiamo lavorato","voi":"avete lavorato","loro":"hanno lavorato"},"futuro":{"io":"lavorerò","tu":"lavorerai","lei":"lavorerà","noi":"lavoreremo","voi":"lavorerete","loro":"lavoreranno"}}},
            {"verb":"Giocare","conjugation":{"presente":{"io":"gioco","tu":"giochi","lei":"gioca","noi":"giochiamo","voi":"giocate","loro":"giocano"},"imperfetto":{"io":"giocavo","tu":"giocavi","lei":"giocava","noi":"giocavamo","voi":"giocavate","loro":"giocavano"},"passato":{"io":"ho giocato","tu":"hai giocato","lei":"ha giocato","noi":"abbiamo giocato","voi":"avete giocato","loro":"hanno giocato"},"futuro":{"io":"giocherò","tu":"giocherai","lei":"giocherà","noi":"giocheremo","voi":"giocherete","loro":"giocheranno"}}},
            {"verb":"Studiare","conjugation":{"presente":{"io":"studio","tu":"studi","lei":"studia","noi":"studiamo","voi":"studiate","loro":"studiano"},"imperfetto":{"io":"studiavo","tu":"studiavi","lei":"studiava","noi":"studiavamo","voi":"studiavate","loro":"studiavano"},"passato":{"io":"ho studiato","tu":"hai studiato","lei":"ha studiato","noi":"abbiamo studiato","voi":"avete studiato","loro":"hanno studiato"},"futuro":{"io":"studierò","tu":"studierai","lei":"studierà","noi":"studieremo","voi":"studierete","loro":"studieranno"}}},
            {"verb":"Cercare","conjugation":{"presente":{"io":"cerco","tu":"cerchi","lei":"cerca","noi":"cerchiamo","voi":"cercate","loro":"cercano"},"imperfetto":{"io":"cercavo","tu":"cercavi","lei":"cercava","noi":"cercavamo","voi":"cercavate","loro":"cercavano"},"passato":{"io":"ho cercato","tu":"hai cercato","lei":"ha cercato","noi":"abbiamo cercato","voi":"avete cercato","loro":"hanno cercato"},"futuro":{"io":"cercherò","tu":"cercherai","lei":"cercherà","noi":"cercheremo","voi":"cercherete","loro":"cercheranno"}}},
            {"verb":"Camminare","conjugation":{"presente":{"io":"cammino","tu":"cammini","lei":"cammina","noi":"camminiamo","voi":"camminate","loro":"camminano"},"imperfetto":{"io":"camminavo","tu":"camminavi","lei":"camminava","noi":"camminavamo","voi":"camminavate","loro":"camminavano"},"passato":{"io":"ho camminato","tu":"hai camminato","lei":"ha camminato","noi":"abbiamo camminato","voi":"avete camminato","loro":"hanno camminato"},"futuro":{"io":"camminerò","tu":"camminerai","lei":"camminerà","noi":"cammineremo","voi":"camminerete","loro":"cammineranno"}}},
            {"verb":"Correre","conjugation":{"presente":{"io":"corro","tu":"corri","lei":"corre","noi":"corriamo","voi":"correte","loro":"corrono"},"imperfetto":{"io":"correvo","tu":"correvi","lei":"correva","noi":"correvamo","voi":"correvate","loro":"correvano"},"passato":{"io":"ho corso","tu":"hai corso","lei":"ha corso","noi":"abbiamo corso","voi":"avete corso","loro":"hanno corso"},"futuro":{"io":"correrò","tu":"correrai","lei":"correrà","noi":"correremo","voi":"correrete","loro":"correranno"}}},
            {"verb":"Dormire","conjugation":{"presente":{"io":"dormo","tu":"dormi","lei":"dorme","noi":"dormiamo","voi":"dormite","loro":"dormono"},"imperfetto":{"io":"dormivo","tu":"dormivi","lei":"dormiva","noi":"dormivamo","voi":"dormivate","loro":"dormivano"},"passato":{"io":"ho dormito","tu":"hai dormito","lei":"ha dormito","noi":"abbiamo dormito","voi":"avete dormito","loro":"hanno dormito"},"futuro":{"io":"dormirò","tu":"dormirai","lei":"dormirà","noi":"dormiremo","voi":"dormirete","loro":"dormiranno"}}},
            {"verb":"Entrare","conjugation":{"presente":{"io":"entro","tu":"entri","lei":"entra","noi":"entriamo","voi":"entrate","loro":"entrano"},"imperfetto":{"io":"entravo","tu":"entravi","lei":"entrava","noi":"entravamo","voi":"entravate","loro":"entravano"},"passato":{"io":"sono entrato/a","tu":"sei entrato/a","lei":"è entrato/a","noi":"siamo entrati/e","voi":"siete entrati/e","loro":"sono entrati/e"},"futuro":{"io":"entrerò","tu":"entrerai","lei":"entrerà","noi":"entreremo","voi":"entrerete","loro":"entreranno"}}},
            {"verb":"Uscire","conjugation":{"presente":{"io":"esco","tu":"esci","lei":"esce","noi":"usciamo","voi":"uscite","loro":"escono"},"imperfetto":{"io":"uscivo","tu":"uscivi","lei":"usciva","noi":"uscivamo","voi":"uscivate","loro":"uscivano"},"passato":{"io":"sono uscito/a","tu":"sei uscito/a","lei":"è uscito/a","noi":"siamo usciti/e","voi":"siete usciti/e","loro":"sono usciti/e"},"futuro":{"io":"uscirò","tu":"uscirai","lei":"uscirà","noi":"usciremo","voi":"uscirete","loro":"usciranno"}}},
            {"verb":"Arrivare","conjugation":{"presente":{"io":"arrivo","tu":"arrivi","lei":"arriva","noi":"arriviamo","voi":"arrivate","loro":"arrivano"},"imperfetto":{"io":"arrivavo","tu":"arrivavi","lei":"arrivava","noi":"arrivavamo","voi":"arrivavate","loro":"arrivavano"},"passato":{"io":"sono arrivato/a","tu":"sei arrivato/a","lei":"è arrivato/a","noi":"siamo arrivati/e","voi":"siete arrivati/e","loro":"sono arrivati/e"},"futuro":{"io":"arriverò","tu":"arriverai","lei":"arriverà","noi":"arriveremo","voi":"arriverete","loro":"arriveranno"}}},
            {"verb":"Partire","conjugation":{"presente":{"io":"parto","tu":"parti","lei":"parte","noi":"partiamo","voi":"partite","loro":"partono"},"imperfetto":{"io":"partivo","tu":"partivi","lei":"partiva","noi":"partivamo","voi":"partivate","loro":"partivano"},"passato":{"io":"sono partito/a","tu":"sei partito/a","lei":"è partito/a","noi":"siamo partiti/e","voi":"siete partiti/e","loro":"sono partiti/e"},"futuro":{"io":"partirò","tu":"partirai","lei":"partirà","noi":"partiremo","voi":"partirete","loro":"partiranno"}}},
            {"verb":"Guidare","conjugation":{"presente":{"io":"guido","tu":"guidi","lei":"guida","noi":"guidiamo","voi":"guidate","loro":"guidano"},"imperfetto":{"io":"guidavo","tu":"guidavi","lei":"guidava","noi":"guidavamo","voi":"guidavate","loro":"guidavano"},"passato":{"io":"ho guidato","tu":"hai guidato","lei":"ha guidato","noi":"abbiamo guidato","voi":"avete guidato","loro":"hanno guidato"},"futuro":{"io":"guiderò","tu":"guiderai","lei":"guiderà","noi":"guideremo","voi":"guiderete","loro":"guideranno"}}},
            {"verb":"Salire","conjugation":{"presente":{"io":"salgo","tu":"sali","lei":"sale","noi":"saliamo","voi":"salite","loro":"salgono"},"imperfetto":{"io":"salivo","tu":"salivi","lei":"saliva","noi":"salivamo","voi":"salivate","loro":"salivano"},"passato":{"io":"sono salito","tu":"sei salito","lei":"è salita","noi":"siamo saliti","voi":"siete saliti","loro":"sono saliti"},"futuro":{"io":"salirò","tu":"salirai","lei":"salirà","noi":"saliremo","voi":"salirete","loro":"saliranno"}}},
            {"verb":"Scendere","conjugation":{"presente":{"io":"scendo","tu":"scendi","lei":"scende","noi":"scendiamo","voi":"scendete","loro":"scendono"},"imperfetto":{"io":"scendevo","tu":"scendevi","lei":"scendeva","noi":"scendevamo","voi":"scendevate","loro":"scendevano"},"passato":{"io":"sono sceso/a","tu":"sei sceso/a","lei":"è sceso/a","noi":"siamo scesi/e","voi":"siete scesi/e","loro":"sono scesi/e"},"futuro":{"io":"scenderò","tu":"scenderai","lei":"scenderà","noi":"scenderemo","voi":"scenderete","loro":"scenderanno"}}},
            {"verb":"Guadagnare","conjugation":{"presente":{"io":"guadagno","tu":"guadagni","lei":"guadagna","noi":"guadagniamo","voi":"guadagnate","loro":"guadagnano"},"imperfetto":{"io":"guadagnavo","tu":"guadagnavi","lei":"guadagnava","noi":"guadagnavamo","voi":"guadagnavate","loro":"guadagnavano"},"passato":{"io":"ho guadagnato","tu":"hai guadagnato","lei":"ha guadagnato","noi":"abbiamo guadagnato","voi":"avete guadagnato","loro":"hanno guadagnato"},"futuro":{"io":"guadagnerò","tu":"guadagnerai","lei":"guadagnerà","noi":"guadagneremo","voi":"guadagnerete","loro":"guadagneranno"}}}
        ]
    },
    {
        "category": "reflexive",
        "verbs": [
            {"verb":"Alzarsi","conjugation":{"presente":{"io":"mi alzo","tu":"ti alzi","lei":"si alza","noi":"ci alziamo","voi":"vi alzate","loro":"si alzano"},"imperfetto":{"io":"mi alzavo","tu":"ti alzavi","lei":"si alzava","noi":"ci alzavamo","voi":"vi alzavate","loro":"si alzavano"},"passato":{"io":"mi sono alzato/a","tu":"ti sei alzato/a","lei":"si è alzato/a","noi":"ci siamo alzati/e","voi":"vi siete alzati/e","loro":"si sono alzati/e"},"futuro":{"io":"mi alzerò","tu":"ti alzerai","lei":"si alzerà","noi":"ci alzeremo","voi":"vi alzerete","loro":"si alzeranno"}}},
            {"verb":"Lavarsi","conjugation":{"presente":{"io":"mi lavo","tu":"ti lavi","lei":"si lava","noi":"ci laviamo","voi":"vi lavate","loro":"si lavano"},"imperfetto":{"io":"mi lavavo","tu":"ti lavavi","lei":"si lavava","noi":"ci lavavamo","voi":"vi lavavate","loro":"si lavavano"},"passato":{"io":"mi sono lavato/a","tu":"ti sei lavato/a","lei":"si è lavato/a","noi":"ci siamo lavati/e","voi":"vi siete lavati/e","loro":"si sono lavati/e"},"futuro":{"io":"mi laverò","tu":"ti laverai","lei":"si laverà","noi":"ci laveremo","voi":"vi laverete","loro":"si laveranno"}}},
            {"verb":"Vestirsi","conjugation":{"presente":{"io":"mi vesto","tu":"ti vesti","lei":"si veste","noi":"ci vestiamo","voi":"vi vestite","loro":"si vestono"},"imperfetto":{"io":"mi vestivo","tu":"ti vestivi","lei":"si vestiva","noi":"ci vestivamo","voi":"vi vestivate","loro":"si vestivano"},"passato":{"io":"mi sono vestito/a","tu":"ti sei vestito/a","lei":"si è vestito/a","noi":"ci siamo vestiti/e","voi":"vi siete vestiti/e","loro":"si sono vestiti/e"},"futuro":{"io":"mi vestirò","tu":"ti vestirai","lei":"si vestirà","noi":"ci vestiremo","voi":"vi vestirete","loro":"si vestiranno"}}},
            {"verb":"Svegliarsi","conjugation":{"presente":{"io":"mi sveglio","tu":"ti svegli","lei":"si sveglia","noi":"ci svegliamo","voi":"vi svegliate","loro":"si svegliano"},"imperfetto":{"io":"mi svegliavo","tu":"ti svegliavi","lei":"si svegliava","noi":"ci svegliavamo","voi":"vi svegliavate","loro":"si svegliavano"},"passato":{"io":"mi sono svegliato/a","tu":"ti sei svegliato/a","lei":"si è svegliato/a","noi":"ci siamo svegliati/e","voi":"vi siete svegliati/e","loro":"si sono svegliati/e"},"futuro":{"io":"mi sveglierò","tu":"ti sveglierai","lei":"si sveglierà","noi":"ci sveglieremo","voi":"vi sveglierete","loro":"si sveglieranno"}}},
            {"verb":"Addormentarsi","conjugation":{"presente":{"io":"mi addormento","tu":"ti addormenti","lei":"si addormenta","noi":"ci addormentiamo","voi":"vi addormentate","loro":"si addormentano"},"imperfetto":{"io":"mi addormentavo","tu":"ti addormentavi","lei":"si addormentava","noi":"ci addormentavamo","voi":"vi addormentavate","loro":"si addormentavano"},"passato":{"io":"mi sono addormentato/a","tu":"ti sei addormentato/a","lei":"si è addormentato/a","noi":"ci siamo addormentati/e","voi":"vi siete addormentati/e","loro":"si sono addormentati/e"},"futuro":{"io":"mi addormenterò","tu":"ti addormenterai","lei":"si addormenterà","noi":"ci addormenteremo","voi":"vi addormenterete","loro":"si addormenteranno"}}},
            {"verb":"Divertirsi","conjugation":{"presente":{"io":"mi diverto","tu":"ti diverti","lei":"si diverte","noi":"ci divertiamo","voi":"vi divertite","loro":"si divertono"},"imperfetto":{"io":"mi divertivo","tu":"ti divertivi","lei":"si divertiva","noi":"ci divertivamo","voi":"vi divertivate","loro":"si divertivano"},"passato":{"io":"mi sono divertito/a","tu":"ti sei divertito/a","lei":"si è divertito/a","noi":"ci siamo divertiti/e","voi":"vi siete divertiti/e","loro":"si sono divertiti/e"},"futuro":{"io":"mi divertirò","tu":"ti divertirai","lei":"si divertirà","noi":"ci divertiremo","voi":"vi divertirete","loro":"si divertiranno"}}},
            {"verb":"Riposarsi","conjugation":{"presente":{"io":"mi riposo","tu":"ti riposi","lei":"si riposa","noi":"ci riposiamo","voi":"vi riposate","loro":"si riposano"},"imperfetto":{"io":"mi riposavo","tu":"ti riposavi","lei":"si riposava","noi":"ci riposavamo","voi":"vi riposavate","loro":"si riposavano"},"passato":{"io":"mi sono riposato/a","tu":"ti sei riposato/a","lei":"si è riposato/a","noi":"ci siamo riposati/e","voi":"vi siete riposati/e","loro":"si sono riposati/e"},"futuro":{"io":"mi riposerò","tu":"ti riposerai","lei":"si riposerà","noi":"ci riposeremo","voi":"vi riposerete","loro":"si riposeranno"}}},
            {"verb":"Sentirsi","conjugation":{"presente":{"io":"mi sento","tu":"ti senti","lei":"si sente","noi":"ci sentiamo","voi":"vi sentite","loro":"si sentono"},"imperfetto":{"io":"mi sentivo","tu":"ti sentivi","lei":"si sentiva","noi":"ci sentivamo","voi":"vi sentivate","loro":"si sentivano"},"passato":{"io":"mi sono sentito/a","tu":"ti sei sentito/a","lei":"si è sentito/a","noi":"ci siamo sentiti/e","voi":"vi siete sentiti/e","loro":"si sono sentiti/e"},"futuro":{"io":"mi sentirò","tu":"ti sentirai","lei":"si sentirà","noi":"ci sentiremo","voi":"vi sentirete","loro":"si sentiranno"}}},
            {"verb":"Chiamarsi","conjugation":{"presente":{"io":"mi chiamo","tu":"ti chiami","lei":"si chiama","noi":"ci chiamiamo","voi":"vi chiamate","loro":"si chiamano"},"imperfetto":{"io":"mi chiamavo","tu":"ti chiamavi","lei":"si chiamava","noi":"ci chiamavamo","voi":"vi chiamavate","loro":"si chiamavano"},"passato":{"io":"mi sono chiamato/a","tu":"ti sei chiamato/a","lei":"si è chiamato/a","noi":"ci siamo chiamati/e","voi":"vi siete chiamati/e","loro":"si sono chiamati/e"},"futuro":{"io":"mi chiamerò","tu":"ti chiamerai","lei":"si chiamerà","noi":"ci chiameremo","voi":"vi chiamerete","loro":"si chiameranno"}}},
            {"verb":"Arrabbiarsi","conjugation":{"presente":{"io":"mi arrabbio","tu":"ti arrabbi","lei":"si arrabbia","noi":"ci arrabbiamo","voi":"vi arrabbiate","loro":"si arrabbiano"},"imperfetto":{"io":"mi arrabbiavo","tu":"ti arrabbiavi","lei":"si arrabbiava","noi":"ci arrabbiavamo","voi":"vi arrabbiavate","loro":"si arrabbiavano"},"passato":{"io":"mi sono arrabbiato/a","tu":"ti sei arrabbiato/a","lei":"si è arrabbiato/a","noi":"ci siamo arrabbiati/e","voi":"vi siete arrabbiati/e","loro":"si sono arrabbiati/e"},"futuro":{"io":"mi arrabbierò","tu":"ti arrabbierai","lei":"si arrabbierà","noi":"ci arrabbieremo","voi":"vi arrabbierete","loro":"si arrabbieranno"}}},
            {"verb":"Preoccuparsi","conjugation":{"presente":{"io":"mi preoccupo","tu":"ti preoccupi","lei":"si preoccupa","noi":"ci preoccupiamo","voi":"vi preoccupate","loro":"si preoccupano"},"imperfetto":{"io":"mi preoccupavo","tu":"ti preoccupavi","lei":"si preoccupava","noi":"ci preoccupavamo","voi":"vi preoccupavate","loro":"si preoccupavano"},"passato":{"io":"mi sono preoccupato/a","tu":"ti sei preoccupato/a","lei":"si è preoccupato/a","noi":"ci siamo preoccupati/e","voi":"vi siete preoccupati/e","loro":"si sono preoccupati/e"},"futuro":{"io":"mi preoccuperò","tu":"ti preoccuperai","lei":"si preoccuperà","noi":"ci preoccuperemo","voi":"vi preoccuperete","loro":"si preoccuperanno"}}},
            {"verb":"Rilassarsi","conjugation":{"presente":{"io":"mi rilasso","tu":"ti rilassi","lei":"si rilassa","noi":"ci rilassiamo","voi":"vi rilassate","loro":"si rilassano"},"imperfetto":{"io":"mi rilassavo","tu":"ti rilassavi","lei":"si rilassava","noi":"ci rilassavamo","voi":"vi rilassavate","loro":"si rilassavano"},"passato":{"io":"mi sono rilassato/a","tu":"ti sei rilassato/a","lei":"si è rilassato/a","noi":"ci siamo rilassati/e","voi":"vi siete rilassati/e","loro":"si sono rilassati/e"},"futuro":{"io":"mi rilasserò","tu":"ti rilasserai","lei":"si rilasserà","noi":"ci rilasseremo","voi":"vi rilasserete","loro":"si rilasseranno"}}},
            {"verb":"Comportarsi","conjugation":{"presente":{"io":"mi comporto","tu":"ti comporti","lei":"si comporta","noi":"ci comportiamo","voi":"vi comportate","loro":"si comportano"},"imperfetto":{"io":"mi comportavo","tu":"ti comportavi","lei":"si comportava","noi":"ci comportavamo","voi":"vi comportavate","loro":"si comportavano"},"passato":{"io":"mi sono comportato/a","tu":"ti sei comportato/a","lei":"si è comportato/a","noi":"ci siamo comportati/e","voi":"vi siete comportati/e","loro":"si sono comportati/e"},"futuro":{"io":"mi comporterò","tu":"ti comporterai","lei":"si comporterà","noi":"ci comporteremo","voi":"vi comporterete","loro":"si comporteranno"}}},
            {"verb":"Innamorarsi","conjugation":{"presente":{"io":"mi innamoro","tu":"ti innamori","lei":"si innamora","noi":"ci innamoriamo","voi":"vi innamorate","loro":"si innamorano"},"imperfetto":{"io":"mi innamoravo","tu":"ti innamoravi","lei":"si innamorava","noi":"ci innamoravamo","voi":"vi innamoravate","loro":"si innamoravano"},"passato":{"io":"mi sono innamorato/a","tu":"ti sei innamorato/a","lei":"si è innamorato/a","noi":"ci siamo innamorati/e","voi":"vi siete innamorati/e","loro":"si sono innamorati/e"},"futuro":{"io":"mi innamorerò","tu":"ti innamorerai","lei":"si innamorerà","noi":"ci innamoreremo","voi":"vi innamorerete","loro":"si innamoreranno"}}},
            {"verb":"Mettersi","conjugation":{"presente":{"io":"mi metto","tu":"ti metti","lei":"si mette","noi":"ci mettiamo","voi":"vi mettete","loro":"si mettono"},"imperfetto":{"io":"mi mettevo","tu":"ti mettevi","lei":"si metteva","noi":"ci mettevamo","voi":"vi mettevate","loro":"si mettevano"},"passato":{"io":"mi sono messo/a","tu":"ti sei messo/a","lei":"si è messo/a","noi":"ci siamo messi/e","voi":"vi siete messi/e","loro":"si sono messi/e"},"futuro":{"io":"mi metterò","tu":"ti metterai","lei":"si metterà","noi":"ci metteremo","voi":"vi metterete","loro":"si metteranno"}}},
            {"verb":"Concentrarsi","conjugation":{"presente":{"io":"mi concentro","tu":"ti concentri","lei":"si concentra","noi":"ci concentriamo","voi":"vi concentrate","loro":"si concentrano"},"imperfetto":{"io":"mi concentravo","tu":"ti concentravi","lei":"si concentrava","noi":"ci concentravamo","voi":"vi concentravate","loro":"si concentravano"},"passato":{"io":"mi sono concentrato/a","tu":"ti sei concentrato/a","lei":"si è concentrato/a","noi":"ci siamo concentrati/e","voi":"vi siete concentrati/e","loro":"si sono concentrati/e"},"futuro":{"io":"mi concentrerò","tu":"ti concentrerai","lei":"si concentrerà","noi":"ci concentreremo","voi":"vi concentrerete","loro":"si concentreranno"}}},
            {"verb":"Baciarsi","conjugation":{"presente":{"io":"mi bacio","tu":"ti baci","lei":"si bacia","noi":"ci baciamo","voi":"vi baciate","loro":"si baciano"},"imperfetto":{"io":"mi baciavo","tu":"ti baciavi","lei":"si baciava","noi":"ci baciavamo","voi":"vi baciavate","loro":"si baciavano"},"passato":{"io":"mi sono baciato/a","tu":"ti sei baciato/a","lei":"si è baciato/a","noi":"ci siamo baciati/e","voi":"vi siete baciati/e","loro":"si sono baciati/e"},"futuro":{"io":"mi bacerò","tu":"ti bacerai","lei":"si bacerà","noi":"ci baceremo","voi":"vi bacerete","loro":"si baceranno"}}},
            {"verb":"Abbracciarsi","conjugation":{"presente":{"io":"mi abbraccio","tu":"ti abbracci","lei":"si abbraccia","noi":"ci abbracciamo","voi":"vi abbracciate","loro":"si abbracciano"},"imperfetto":{"io":"mi abbracciavo","tu":"ti abbracciavi","lei":"si abbracciava","noi":"ci abbracciavamo","voi":"vi abbracciavate","loro":"si abbracciavano"},"passato":{"io":"mi sono abbracciato/a","tu":"ti sei abbracciato/a","lei":"si è abbracciato/a","noi":"ci siamo abbracciati/e","voi":"vi siete abbracciati/e","loro":"si sono abbracciati/e"},"futuro":{"io":"mi abbraccerò","tu":"ti abbraccerai","lei":"si abbraccerà","noi":"ci abbracceremo","voi":"vi abbraccerete","loro":"si abbracceranno"}}},
            {"verb":"Riunirsi","conjugation":{"presente":{"io":"mi riunisco","tu":"ti riunisci","lei":"si riunisce","noi":"ci riuniamo","voi":"vi riunite","loro":"si riuniscono"},"imperfetto":{"io":"mi riunivo","tu":"ti riunivi","lei":"si riuniva","noi":"ci riunivamo","voi":"vi riunivate","loro":"si riunivano"},"passato":{"io":"mi sono riunito/a","tu":"ti sei riunito/a","lei":"si è riunito/a","noi":"ci siamo riuniti/e","voi":"vi siete riuniti/e","loro":"si sono riuniti/e"},"futuro":{"io":"mi riunirò","tu":"ti riunirai","lei":"si riunirà","noi":"ci riuniremo","voi":"vi riunirete","loro":"si riuniranno"}}},
            {"verb":"Perdersi","conjugation":{"presente":{"io":"mi perdo","tu":"ti perdi","lei":"si perde","noi":"ci perdiamo","voi":"vi perdete","loro":"si perdono"},"imperfetto":{"io":"mi perdevo","tu":"ti perdevi","lei":"si perdeva","noi":"ci perdevamo","voi":"vi perdevate","loro":"si perdevano"},"passato":{"io":"mi sono perso/a","tu":"ti sei perso/a","lei":"si è perso/a","noi":"ci siamo persi/e","voi":"vi siete persi/e","loro":"si sono persi/e"},"futuro":{"io":"mi perderò","tu":"ti perderai","lei":"si perderà","noi":"ci perderemo","voi":"vi perderete","loro":"si perderanno"}}}
        ]
    }
]